blank_issues_enabled: true
contact_links:
  - name: Discord Bot Support
    url: https://discord.gg/uRvPVf7Kcp
    about: Ask questions here for quicker support
  - name: Trello
    url: https://trello.com/b/37CS9Aju
    about: Known issues and planned features for the bot.
  - name: Docs
    url: https://galactic-bot.readthedocs.io
    about: Get the documentation for Galactic(WIP)
