blank_issues_enabled: false
contact_links:
  - name: Discord Bot Support
    url: https://discord.gg/uRvPVf7Kcp
    about: Ask questions here for quicker support
  - name: Trello
    url: https://trello.com/b/37CS9Aju
    about: Known issues and planned features for the bot.
